FROM grafana/grafana:10.3.4

COPY ./provisioning/datasources /etc/grafana/provisioning/datasources
COPY ./provisioning/dashboards /etc/grafana/provisioning/dashboards

COPY ./grafana.ini /etc/grafana/grafana.ini